CREATE DATABASE IF NOT EXISTS COCOCACA;

USE COCOCACA;

CREATE TABLE IF NOT EXISTS T_SUBSCRIBER (ID VARCHAR (128), NAME VARCHAR (128), PASSWORD VARCHAR (128), GENDER VARCHAR (32), AVATAR VARCHAR (128));

CREATE TABLE IF NOT EXISTS TC_FOLLOWSHIP (NAME VARCHAR (128), FOLLOWER VARCHAR (128)); 

CREATE TABLE IF NOT EXISTS T_POST (ID VARCHAR (128), AUTHOR_ID VARCHAR (128), CONTENT_ID VARCHAR (128), DESCRIPTION VARCHAR (128));

CREATE TABLE IF NOT EXISTS T_DANMUKU (ID VARCHAR (128), AUTHOR_ID VARCHAR (128), CONTENT VARCHAR (128), TIMESTAMP VARCHAR (128));

CREATE TABLE IF NOT EXISTS T_IMG (ID VARCHAR (128), DATA VARCHAR (128));
